### ISSUE TITLE
Avoid handling the error flow 

### ISSUE THREAD

**Issue by h4cc** [voodoo-child/gmex#1]
There is a nice construct named `with` in Elixir to handle the {:ok, _} and {:error, _} pattern.

To something like this should not be necessary:

`def save( image = { :ok, options }, dest_path ) do`

If you want to keep it, add a match that does not expect a tuple as first argument:

`def save( image, dest_path ) do`

**Comment by dpostolachi** [comment]
@h4cc , could you please check it out if it's okay so I can close the issue?

**Comment by h4cc** [comment]
I am missing the `@type Image` for dializer :/

How about using a struct like this for the image?

```
defstruct Gmex.Image do
  defstruct [
    image: nil,
    options: [],
  ]
end
```

**Comment by dpostolachi** [comment]
Yeah, the struct is a good idea, will add it.
