### ISSUE TITLE
Support setting multiple options at once

### ISSUE THREAD

**Issue by h4cc** [voodoo-child/gmex#2]
How about extending this signature to support a keyword list as second argument?

`def option( image = { :ok, options }, option ) do`

Then this would be possible:

`... |> option(width: 400, height: 600, grayscale: true) |> ...`

**Comment by dpostolachi** [comment]
@h4cc I like the idea, will work on that.

**Comment by dpostolachi** [comment]
Added support for multiple options with a new function `options/2`

```
  |> options( negate: true, resize: { 50, 50 }, strip: true, format: "jpg" )
```
