### ISSUE TITLE
Make name and path to `gm` binary portable

### ISSUE THREAD

**Issue by h4cc** [voodoo-child/gmex#3]
Currently the name of the binary is hardcoded. This could be in the options too.

Is there like a check or error handling the case when the binary is missing?

**Comment by dpostolachi** [comment]
Just added support for custom binary path option that defaults to `gm`:
```elixir
Gmex.open( "test/images/blossom.jpg", gm_path: "/usr/local/bin/gm" )
```
In case binary is missing it will return
```elixir
{ :error, "graphicsmagick executable not found at:/usr/local/bin/gm" }
```

Commit 4433729c80efde3d4285cd5be77bab759a36e874

**Comment by h4cc** [comment]
:+1:
